# Generated by Django 4.2.7 on 2025-07-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Student's full name", max_length=255)),
                ('email', models.EmailField(help_text="Student's email address", max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('semester', models.CharField(help_text='Current semester', max_length=255)),
                ('department', models.CharField(help_text='Department/course', max_length=255)),
                ('hostel', models.CharField(help_text='Hostel name', max_length=255)),
                ('location', models.CharField(help_text='Location/room details', max_length=255)),
                ('complaint_text', models.TextField(help_text='Detailed complaint')),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('complaint_status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', help_text='Complaint status', max_length=255)),
                ('complaint_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'ordering': ['-complaint_date'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the hostel', max_length=255)),
                ('address', models.TextField(help_text='Full address of the hostel')),
                ('owner_name', models.CharField(help_text='Name of the hostel owner', max_length=255)),
                ('contact_details', models.CharField(help_text='Contact information', max_length=255)),
                ('total_capacity', models.PositiveIntegerField(default=0, help_text='Total bed capacity')),
                ('current_vacancy', models.PositiveIntegerField(help_text='Currently available beds')),
                ('mens_or_ladies', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Mixed', 'Mixed')], help_text='Gender preference', max_length=10)),
                ('average_rent', models.PositiveIntegerField(help_text='Average monthly rent')),
                ('accommodation_type', models.CharField(help_text='Type of accommodation', max_length=50)),
                ('curfew', models.TimeField(blank=True, help_text='Curfew time (optional)', null=True)),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('mess', models.TextField(blank=True, default=None, help_text='Mess facility details', null=True)),
                ('distance', models.FloatField(default=0.0, help_text='Distance from college in km')),
                ('approval_hostel_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Approval status', max_length=255)),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the hostel', max_length=255)),
                ('address', models.TextField(help_text='Full address of the hostel')),
                ('owner_name', models.CharField(help_text='Name of the hostel owner', max_length=255)),
                ('contact_details', models.CharField(help_text='Contact information', max_length=255)),
                ('total_capacity', models.PositiveIntegerField(help_text='Total bed capacity')),
                ('current_vacancy', models.PositiveIntegerField(help_text='Currently available beds')),
                ('mens_or_ladies', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Mixed', 'Mixed')], help_text='Gender preference', max_length=10)),
                ('average_rent', models.PositiveIntegerField(help_text='Average monthly rent')),
                ('accommodation_type', models.CharField(help_text='Type of accommodation (Hostel/PG)', max_length=50)),
                ('curfew', models.TimeField(blank=True, help_text='Curfew time (optional)', null=True)),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('distance', models.FloatField(default=0.0, help_text='Distance from college in km')),
                ('mess', models.CharField(default='No', help_text='Mess facility availability (Yes/No)', max_length=10)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Request approval status', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes or rejection reason', null=True)),
            ],
            options={
                'verbose_name': 'Hostel Registration Request',
                'verbose_name_plural': 'Hostel Registration Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelname', models.CharField(help_text='Name of the hostel', max_length=255)),
                ('vacancycount', models.PositiveIntegerField(help_text='Number of vacant rooms')),
                ('approved', models.BooleanField(default=False, help_text='Approval status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(blank=True, help_text='Related hostel (if exists)', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hostel')),
            ],
            options={
                'verbose_name': 'Vacancy Request',
                'verbose_name_plural': 'Vacancy Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
