# Generated by Django 4.2.7 on 2025-07-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancycount',
            field=models.IntegerField(help_text='Number of vacant rooms (positive to add, negative to remove)'),
        ),
    ]
