# Generated by Django 4.2.7 on 2023-12-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="grievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("hostel", models.CharField(max_length=255)),
                ("room", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
    ]
