# Generated by Django 4.2.7 on 2023-12-02 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_grievance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grievance",
            name="description",
        ),
        migrations.RemoveField(
            model_name="grievance",
            name="email",
        ),
        migrations.RemoveField(
            model_name="grievance",
            name="hostel",
        ),
        migrations.RemoveField(
            model_name="grievance",
            name="name",
        ),
        migrations.RemoveField(
            model_name="grievance",
            name="room",
        ),
        migrations.RemoveField(
            model_name="grievance",
            name="status",
        ),
    ]
