# Generated by Django 4.2.7 on 2025-07-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_vacancy_vacancycount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancycount',
            field=models.PositiveIntegerField(help_text='Number of vacant rooms'),
        ),
    ]
