# Generated by Django 4.2.7 on 2023-12-04 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_grievance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Grievance",
        ),
    ]
