# Generated by Django 4.2.7 on 2023-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="curfew",
            field=models.TimeField(default=None),
        ),
    ]
