# Generated by Django 4.2.7 on 2023-12-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_hostel_average_rent"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="distance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="hostel",
            name="mess",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
