# Generated by Django 4.2.7 on 2023-12-05 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_hostel_distance_hostel_mess"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Grievance",
        ),
    ]
