# Generated by Django 5.0.6 on 2024-07-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_grievance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelname', models.CharField(max_length=30)),
                ('vacancycount', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
