# Generated by Django 5.0.6 on 2024-07-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_vacancy_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='approval_hostel_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
