# Fly.io Configuration
app = "privatehostelscet"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  DJANGO_SETTINGS_MODULE = "myapp.settings"
  PORT = "8000"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
